FROM dalibo/buildpack-python:bullseye

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        postgresql-13 postgresql-client-13 postgresql-contrib-13 \
        postgresql-11 postgresql-client-11 postgresql-contrib-11 \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :
