FROM dalibo/buildpack-python:trixie

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        postgresql-17 postgresql-client-17 postgresql-contrib-17 \
        postgresql-15 postgresql-client-15 postgresql-contrib-15 \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :
