FROM dalibo/buildpack-python:bookworm

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        postgresql-15 postgresql-client-15 postgresql-contrib-15 \
        postgresql-13 postgresql-client-13 postgresql-contrib-13 \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :
