FROM dalibo/buildpack-python:rockylinux8

ADD pgdg-eol.repo /etc/yum.repos.d/pgdg-eol.repo
RUN set -ex; \
    dnf -qy module disable postgresql; \
    yum -qy install \
        postgresql14-server postgresql14-contrib \
        postgresql13-server postgresql13-contrib \
        postgresql12-server postgresql12-contrib \
    ; \
    yum clean all ; \
    :
